### DISCUSSION TITLE
Need help in accessing UI

### DISCUSSION THREAD

**Discussion by sriabhi02nov** [alexandrevilain/temporal-operator#138] [Q&A] [answered]
Hi,

I was not able to figure out how i can access temporal UI deployed via this CRD or can register workflow.
Any inputs or documentation will be helpful.

**Comment by alexandrevilain** [comment, marked as answer]
Hi :) 

You can enable the temporal UI and access it using an ingress by configuring it in the TemporalCluster CRD:

```yaml
apiVersion: apps.alexandrevilain.dev/v1alpha1
kind: TemporalCluster
metadata:
  name: prod
  namespace: demo
spec:
  version: 1.17.4
  numHistoryShards: 1
  # [...]
  ui:
    enabled: true
    ingress:
      ingressClassName: nginx
```

You can checkout the documentation here: https://github.com/alexandrevilain/temporal-operator/blob/v0.6.2/docs/api/v1alpha1.md#temporaluispec

Note that if you're running 0.6.2, 0.7.0 will introduce a breaking change on the TemporalCluster API.
