### DISCUSSION TITLE
How add Custom Attributes?

### DISCUSSION THREAD

**Discussion by DodgeCamaro** [alexandrevilain/temporal-operator#451] [General]
I need to use custom attributes, but I've got a 403 error from ES.

**Comment by alexandrevilain** [comment]
Hi @DodgeCamaro !
Hum this seems not related to the operator, did you checked https://community.temporal.io/t/custom-search-attributes-lost-after-1-19-1-20/7597/8 ?

**Reply by DodgeCamaro** [reply]
Hi!
Yes, I've checked this.
Currently, I can't create attributes on my configuration AWS RDS + AWS OpenSearch.
I've tested docker-compose by temporal, temporal-operator with OpenSearch/ElasticSearch + Postgres setup at cluster, they work well.

**Reply by alexandrevilain** [reply]
Could you please share your `TemporalCluster` spec ?

**Reply by DodgeCamaro** [reply]
```
apiVersion: temporal.io/v1beta1
kind: TemporalCluster
metadata:
  name: temporal
spec:
  version: 1.20.4
  numHistoryShards: 4
  metrics:
    enabled: true
    prometheus:
      listenPort: 9090
      scrapeConfig:
        serviceMonitor:
          enabled: true
          labels: 
            release: monitoring
  dynamicConfig:
    pollInterval: 10s
    values:
      frontend.rps:
      - value: 4800
        constraints: {}
      frontend.namespaceCount:
      - value: 2400
        constraints: {}
      limit.blobSize.warn:
      - value: 2MB
        constraints: {}
      limit.blobSize.error:
      - value: 4Mb
        constraints: {}
  archival:
    enabled: true
    provider:
      s3:
        roleName: "${TEMPORAL_ROLE}"
        region: us-east-2
    history:
      enabled: true
      enableRead: true
      path: "${BUCKET}"
      paused: false
    visibility:
      enabled: true
      enableRead: true
      path: "${BUCKET}"
      paused: false
  jobTtlSecondsAfterFinished: 300 
  persistence:
    defaultStore:
      sql:
        user: ${POSTGRES_USER}
        pluginName: postgres
        databaseName: temporal
        connectAddr: "${POSTGRES_HOST}"
        connectProtocol: tcp
      passwordSecretRef:
        name: temporal-frontend
        key: POSTGRES_PWD
    visibilityStore:
      sql:
        user: ${POSTGRES_USER}
        pluginName: postgres
        databaseName: temporal_visibility
        connectAddr: ${POSTGRES_HOST}
        connectProtocol: tcp
      passwordSecretRef:
        name: temporal-frontend
        key: POSTGRES_PWD
    advancedVisibilityStore:
      elasticsearch:
        version: v7
        username: ${OPENSEARCH_USER}
        url: ${OPENSEARCH_HOST}
        enableHealthcheck: true
        indices:
          visibility: temporal_visibility
      passwordSecretRef:
        name: temporal-frontend
        key: OPENSEARCH_PWD
  ui:
    enabled: true
    version: 2.17.2
    replicas: 1
    resources:
      limits:
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ingress:
      ingressClassName: alb    
      hosts:
        - ${HOST}
      annotations:
        alb.ingress.kubernetes.io/target-type: ip
  admintools:
    enabled: false
  services:
    frontend:
      replicas: 1   
      overrides:     
        deployment:
          spec:
            template:
              spec:
                containers:
                  - name: service
                    resources:
                      limits:
                        memory: 1000Mi
                      requests:
                        cpu: 100m
                        memory: 500Mi
                    envFrom:
                      - secretRef:
                          name: temporal-frontend
                affinity:
                  podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                    - labelSelector:
                        matchExpressions:
                        - key: app.kubernetes.io/component
                          operator: In
                          values:
                          - frontend
                          - worker
                          - matching
                          - history
                      topologyKey: kubernetes.io/hostname
    matching:
      replicas: 1
      overrides:
        deployment:
          spec:
            template:
              spec:
                containers:
                  - name: service
                    resources:
                      limits:
                        memory: 1000Mi
                      requests:
                        cpu: 100m
                        memory: 500Mi
                affinity:
                  podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                    - labelSelector:
                        matchExpressions:
                        - key: app.kubernetes.io/component
                          operator: In
                          values:
                          - frontend
                          - worker
                          - matching
                          - history
                      topologyKey: kubernetes.io/hostname
    history:
      replicas: 1
      overrides:
        deployment:
          spec:
            template:
              spec:
                containers:
                  - name: service
                    resources:
                      limits:
                        memory: 1000Mi
                      requests:
                        cpu: 100m
                        memory: 500Mi
                affinity:
                  podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                    - labelSelector:
                        matchExpressions:
                        - key: app.kubernetes.io/component
                          operator: In
                          values:
                          - frontend
                          - worker
                          - matching
                          - history
                      topologyKey: kubernetes.io/hostname
    worker:
      replicas: 1
      overrides:
        deployment:
          spec:
            template:
              spec:
                containers:
                  - name: service
                    resources:
                      limits:
                        memory: 1000Mi
                      requests:
                        cpu: 100m
                        memory: 500Mi
                affinity:
                  podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                    - labelSelector:
                        matchExpressions:
                        - key: app.kubernetes.io/component
                          operator: In
                          values:
                          - frontend
                          - worker
                          - matching
                          - history
                      topologyKey: kubernetes.io/hostname
```
