### ISSUE TITLE
Custom annotations for pods

### ISSUE THREAD

**Issue by bmorton** [alexandrevilain/temporal-operator#170]
Perhaps there is a general operator pattern that I am missing, but I'm looking to add some custom annotations to the pods so that I can tell the Datadog Agent to scrape metrics.  Is there a way I can pass through these annotations from the CRD?  If this is the right way to go about this, but doesn't exist yet, would you take a PR for this?

Thanks for all the work on this operator!  I'm pretty new to operators and have been doing lots of reading, so I'm enjoying poking around this one!

**Comment by alexandrevilain** [comment]
Hi!

First of all, thanks for the feedback! 

You can pass annotations to the temporalcluster itself, and annotations will be propagated to all of the objects.

For instance:
```
apiVersion: temporal.io/v1beta1
kind: TemporalCluster
metadata:
  name: prod
  namespace: demo
  annotations:
    ad.datadoghq.com/temporal.check_names: [""]
spec:
  version: 1.17.4
  # [...]
```

Could you please try and let met now if it suits your needs ? Maybe we can add an extra API field for temporal services to make the operator add some annotations to the pods, or deployments.
