### ISSUE TITLE
SIGSEV on reconciling temporal worker process

### ISSUE THREAD

**Issue by remeq** [alexandrevilain/temporal-operator#197]
Hi,

I am getting following error on reconciling Temporal worker process resource. 

```
1.6692205965847738e+09  INFO    Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference        {"controller": "temporalworkerprocess", "controllerGroup": "temporal.io", "controllerKind": "TemporalWorkerProcess", "TemporalWorkerProcess": {"name":"test","namespace":"dev-stage"}, "namespace": "dev-stage", "name": "test", "reconcileID": "49490e44-9277-4f1d-972c-5c2288ffb791"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1c0a7e6]
```

Please see full log and my manifests in the attachment.

Thanks,
Premek
[temporallogs.tar.gz](https://github.com/alexandrevilain/temporal-operator/files/10077525/temporallogs.tar.gz)

**Comment by alexandrevilain** [comment]
Hi @remeq! 
Thanks for the report! 
According to the log, there is a bug on the operator side. I know how to fix it and I'll do it ASAP.
This bug can be mitigated by settting the `spec.builder.attempt` field, like that:

```yaml
apiVersion: temporal.io/v1beta1
kind: TemporalWorkerProcess
metadata:
  name: test
spec:
  # [...]
  clusterRef:
    name: prod
    namespace: demo
  temporalNamespace: default
  # [...]
  builder:
    attempt: 1 # <-- This is the fix
```

**Comment by alexandrevilain** [comment]
cc @ktenzer

**Comment by remeq** [comment]
@alexandrevilain 

would you have an example of full, working  `spec.builder` spec ? With provided fix it started crashing somewhere else in the code:

```est","namespace":"dev-stage"}, "namespace": "dev-stage", "name": "test", "reconcileID": "352594d7-71ae-4858-99d0-053d246858c3"}
1.669302070867436e+09   INFO    Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference        {"controller": "temporalworkerprocess", "controllerGroup": "temporal.io", "controllerKind": "TemporalWorkerProcess", "TemporalWorkerProcess": {"name":"test","namespace":"dev-stage"}, "namespace": "dev-stage", "name": "test", "reconcileID": "352594d7-71ae-4858-99d0-053d246858c3"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1c1b2f2]

goroutine 1214 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x1dea040, 0x362f4e0})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/alexandrevilain/temporal-operator/controllers.(*TemporalWorkerProcessReconciler).reconcileDefaults(0x0?, {0x0?, 0x0?}, 0xc0009f0540)
        /workspace/controllers/temporalworkerprocess_controller.go:228 +0x92
github.com/alexandrevilain/temporal-operator/controllers.(*TemporalWorkerProcessReconciler).Reconcile(0xc0009722a0, {0x25cffd8, 0xc000e61ec0}, {{{0xc000841da0?, 0x10?}, {0xc000841d98?, 0x40d7a7?}}})
        /workspace/controllers/temporalworkerprocess_controller.go:79 +0x1bb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x25cff30?, {0x25cffd8?, 0xc000e61ec0?}, {{{0xc000841da0?, 0x1fa0460?}, {0xc000841d98?, 0x4041f4?}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121 +0xc8
```

**Comment by alexandrevilain** [comment]
Wow so much bugs ... I'm sorry about that. 
It's because it's missing a gitRepository.

```
apiVersion: temporal.io/v1beta1
kind: TemporalWorkerProcess
metadata:
  name: test
spec:
  # [...]
  clusterRef:
    name: prod
    namespace: demo
  temporalNamespace: default
  # [...]
  builder:
    attempt: 1 # <-- This is the fix
    gitRepository:
      url: https://my-repo.com
```

FYI I'm starting to work on a better workerprocess builder implementation.

**Comment by alexandrevilain** [comment]
Oh ... Are you just trying to use the WorkerProcess and not the builder ?

**Comment by ktenzer** [comment]
Yep sorry for these bugs this was my bad.

First there are two ways to use temporalworkerprocess 1) you can just point it at an image and it will deploy that image. In this case you would change the version which is the version of your docker image and it would deploy new image. 2) you can point it at a git repo and it will build the provided Dockerfile, push it to your repo and then deploy it. If you change the version or buildAttempt it will force a new build, push, deploy. 

The idea is you would have some CI upon checking into your git repo (git actions or something) and then operator would manage CD part. We have plans to integrate with some webhooks but today you need to change either version or buildAttempt to redeploy.

This is example of a spec which would be option 1:
```
spec:
  clusterRef:
    name: prod
    namespace: temporal
  image: ktenzer/helloworld-worker
  jobTtlSecondsAfterFinished: 300
  pullPolicy: Always
  replicas: 3
  temporalNamespace: default
  version: v1.0
```

This is example of a spec which would be option 2:

```
spec:
  builder:
    attempt: 3
    buildDir: samples-go/helloworld
    buildRegistry:
      passwordSecretRef:
        key: PASSWORD
        name: docker-password
      repository: docker.io
      username: ktenzer
    enabled: true
    gitRepository:
      reference:
        branch: main
      url: https://github.com/ktenzer/samples-go.git
    image: quay.io/podman/stable
    version: latest
  clusterRef:
    name: prod
    namespace: temporal
  image: ktenzer/helloworld-worker
  jobTtlSecondsAfterFinished: 300
  pullPolicy: Always
  replicas: 3
  temporalNamespace: default
  version: v1.0
```
Let me know if this helps?

**Comment by remeq** [comment]
@alexandrevilain No problem at all, I understand this is WIP. 

 I am just trying to set up some basic "hello world" -  I want to deploy Temporal Worker Process from the example shown here: https://github.com/alexandrevilain/temporal-operator/tree/main/examples/cluster-postgres

I haven seen the "builder" part nowhere in the examples so I am not sure if I generally need  it (at least for some basic hello world)

**Comment by remeq** [comment]
@ktenzer no problem thanks. Is there any workaround if I want to get option 1 running before fix will be available?

**Comment by ktenzer** [comment]
@remeq You should be able to just set enable: false under builder. Then it will deploy the image, in example below it would be ktenzer/helloworld-worker:v1.0. Let me know if that works?

spec:
  builder:
    attempt: 3
    buildDir: samples-go/helloworld
    buildRegistry:
      passwordSecretRef:
        key: PASSWORD
        name: docker-password
      repository: docker.io
      username: ktenzer
    enabled: false 
    gitRepository:
      reference:
        branch: main
      url: https://github.com/ktenzer/samples-go.git
    image: quay.io/podman/stable
    version: latest
  clusterRef:
    name: prod
    namespace: temporal
  image: ktenzer/helloworld-worker
  jobTtlSecondsAfterFinished: 300
  pullPolicy: Always
  replicas: 3
  temporalNamespace: default
  version: v1.0

**Comment by remeq** [comment]
@ktenzer yes, thanks, it seems to work now - the operator now started provisioning workers

**Comment by ktenzer** [comment]
@remeq awesome yeah we will fix this its just a minor thing with the optional parameters not being optional

**Comment by ktenzer** [comment]
@remeq maybe there was issue with the image. I repushed it and tested and it works using latest. Can you try below spec?

```apiVersion: temporal.io/v1beta1
kind: TemporalWorkerProcess
metadata:
  name: test
spec:
  builder:
    attempt: 3
    buildDir: samples-go/helloworld
    buildRegistry:
      passwordSecretRef:
        key: PASSWORD
        name: docker-password
      repository: docker.io
      username: ktenzer
    enabled: false
    gitRepository:
      reference:
        branch: main
      url: https://github.com/ktenzer/samples-go.git
    image: quay.io/podman/stable
    version: latest
  clusterRef:
    name: prod
    namespace: temporal
  image: ktenzer/helloworld-worker
  jobTtlSecondsAfterFinished: 300
  pullPolicy: Always
  replicas: 3
  temporalNamespace: default
  version: latest```

**Comment by remeq** [comment]
@ktenzer yes, thanks this seems to be working if I set following on the TemporalCluster:
```
  mTLS:
    provider: cert-manager
    internode:
      enabled: false
    frontend:
      enabled: false
```

It doesn't work when I enable mTLS, so I am supposing your example works only with mTLS disabled, correct?

**Comment by ktenzer** [comment]
@remeq The temporalworkerprocess does not yet support mtls so you need to have it disabled,

**Comment by alexandrevilain** [comment]
Hi @remeq, @ktenzer, @rawcode 
The PR fixing this issue is now merged, I'll release v0.10.0 during the day. I'll ping you once available.
Please note that v0.10.0 now requires cert-manager on the cluster.

**Comment by alexandrevilain** [comment]
Hi all, 
Release v0.10.0 is now available 🎉. 
If some of you find time to check if everything is fixed, that would be nice :)

**Comment by remeq** [comment]
> Hi @remeq, @ktenzer, @RawCode The PR fixing this issue is now merged, I'll release v0.10.0 during the day. I'll ping you once available. Please note that v0.10.0 now requires cert-manager on the cluster.

Awesome, thank you very much, will check it out once we will be doing redeployment and will report back

**Comment by rawkode** [comment]
@alexandrevilain This works when we create a new Temporal cluster, but the upgrade from the old release to the new breaks.

I don't have the exact error message any more, I failed to keep it during debugging. But it said something like "Cluster information was duplicated"

**Comment by alexandrevilain** [comment]
Oh, I need to check that. 
Could you please give me more context ?

**Comment by rawkode** [comment]
To reproduce, deploy the Operator (0.9) and add a cluster. My Cluster resource was:

```yaml
new kubernetes.apiextensions.CustomResource("temporal-cluster", {
	apiVersion: "temporal.io/v1beta1",
	kind: "TemporalCluster",
	metadata: {
		// We call this temporalio to avoid conflicts during the UI config rendering.
		// The temporalio/ui container uses `TEMPORAL_UI_PORT` to configure the listening
		// port, which causes a collision with any service called temporal-ui.
		// Let's avoid that
		name: "temporalio",
	},
	spec: {
		version: "1.18.5",
		numHistoryShards: 1,
		jobTtlSecondsAfterFinished: 300,
		persistence: {
			defaultStore: {
				sql: {
					user: postgreSQLUsername,
					databaseName: postgreSQLUsername,
					pluginName: "postgres",
					connectAddr: `${postgreSQLClusterName}-rw:5432`,
					connectProtocol: "tcp",
				},
				passwordSecretRef: {
					name: secret.metadata.name,
					key: "password",
				},
			},
			visibilityStore: {
				sql: {
					user: postgreSQLUsername,
					databaseName: `${postgreSQLUsername}_visibility`,
					pluginName: "postgres",
					connectAddr: `${postgreSQLClusterName}-rw:5432`,
					connectProtocol: "tcp",
				},
				passwordSecretRef: {
					name: secret.metadata.name,
					key: "password",
				},
			},
		},
		mTLS: {
			provider: "cert-manager",
			internode: {
				enabled: true,
			},
			frontend: {
				enabled: true,
			},
			certificatesDuration: {
				rootCACertificate: "2h",
				intermediateCAsCertificates: "1h30m",
				clientCertificates: "1h",
				frontendCertificate: "1h",
				internodeCertificate: "1h",
			},
			refreshInterval: "5m",
		},
		ui: {
			enabled: true,
		},
		admintools: {
			enabled: true,
		},
		metrics: {
			enabled: true,
			prometheusConfig: {
				listenPort: 9090,
			},
		},
	},
});
```


I then upgraded to the latest release of the operator and the error was present.

I'll see if I can find some time today to downgrade and try the upgrade again.
