### ISSUE TITLE
Error with WorkerProcess

### ISSUE THREAD

**Issue by rawkode** [alexandrevilain/temporal-operator#233]
My YAML looks like this:

```yaml
apiVersion: temporal.io/v1beta1
kind: TemporalWorkerProcess
metadata:
  name: test
spec:
  version: latest
  replicas: 3
  image: ghcr.io/rawkodeacademy/studio-workflows-youtube
  pullPolicy: "Always"
  clusterRef:
    name: temporal
    namespace: studio
  temporalNamespace: default
```

My expectation is that this image will be run with enough environment variables to configure the Temporal client for the cluster.

However, we get the following error:

```shell
2023-01-04T17:59:18Z    INFO    Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference        {"controller": "temporalworkerprocess", "controllerGroup": "temporal.io", "controllerKind": "TemporalWorkerProcess", "TemporalWorkerProcess": {"name":"test","namespace":"studio"}, "namespace": "studio", "name": "test", "reconcileID": "f9cbef8c-5b9e-4f6d-b0a2-2c1a72cebf9b"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1cf66c9]

goroutine 448 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x1ef1b00, 0x381ba30})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/alexandrevilain/temporal-operator/pkg/resource/workerprocess.(*DeploymentBuilder).Update(0xc00075e690, {0x26fbfc0?, 0xc00082c500?})
        /workspace/pkg/resource/workerprocess/workerprocess_deployment_builder.go:71 +0x409
github.com/alexandrevilain/temporal-operator/pkg/reconciler.(*Base).ReconcileBuilders.func1()
        /workspace/pkg/reconciler/base.go:133 +0x2d
sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.mutate(0x26c2600?, {{0xc000a3acf0?, 0x0?}, {0xc0005a11c0?, 0x26e2a38?}}, {0x26fbfc0, 0xc00082c500})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/controller/controllerutil/controllerutil.go:339 +0x4f
sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.CreateOrUpdate({0x26e2a38, 0xc000faf920}, {0x26ed068, 0xc0008a73e0}, {0x26fbfc0?, 0xc00082c500}, 0x0?)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/controller/controllerutil/controllerutil.go:201 +0x13f
github.com/alexandrevilain/temporal-operator/pkg/reconciler.(*Base).ReconcileBuilders(0xc000ccb4d0, {0x26e2a38, 0xc000faf920}, {0x26c5db8, 0xc000c9e000}, {0xc0001ba9f0, 0x1, 0x2?})
```

The nil reference appears to be accessing `builder.buildAttempt`, which confused me. So I updated the YAML with:

```yaml
builder:
  enabled: false
```

However, this continues to error - only a little different:

```shell
2023-01-04T18:00:28Z    INFO    Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference        {"controller": "temporalworkerprocess", "controllerGroup": "temporal.io", "controllerKind": "TemporalWorkerProcess", "TemporalWorkerProcess": {"name":"test","namespace":"studio"}, "namespace": "studio", "name": "test", "reconcileID": "8b0ad98b-32d0-4558-8916-bf2a8e7b93a4"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1d07ef2]

goroutine 423 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x1ef1b00, 0x381ba30})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/alexandrevilain/temporal-operator/controllers.(*TemporalWorkerProcessReconciler).reconcileDefaults(0x0?, {0x0?, 0x0?}, 0xc000582700)
        /workspace/controllers/temporalworkerprocess_controller.go:228 +0x92
github.com/alexandrevilain/temporal-operator/controllers.(*TemporalWorkerProcessReconciler).Reconcile(0xc000bb9770, {0x26e2a38, 0xc000c97050}, {{{0xc000bd6244?, 0x10?}, {0xc000bd6240?, 0x40da87?}}})
        /workspace/controllers/temporalworkerprocess_controller.go:79 +0x1bb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x26e2a38?, {0x26e2a38?, 0xc000c97050?}, {{{0xc000bd6244?, 0x1e4dbe0?}, {0xc000bd6240?, 0x0?}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000b76be0, {0x26e2990, 0xc000b50ac0}, {0x1f85960?, 0xc0007de4c0?})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323 +0x38f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000b76be0, {0x26e2990, 0xc000b50ac0})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
```

**Comment by rawkode** [comment]
Perhaps I misunderstand what `WorkerProcess` is for, so please let me know if my expectations are incorrect :)

**Comment by alexandrevilain** [comment]
Hi !
Thanks for the issue :) 
Your issue is known, it's the same as #197. 

The issue you linked is supposed to fix this issue :)

**Comment by alexandrevilain** [comment]
I hope to merge it by the end of the week.

**Comment by rawkode** [comment]
Awesome. Thanks for the update

**Comment by ktenzer** [comment]
@rawkode idea of temporalworkerprocess is to run your temporal worker (client code). There are two options you can provide an image and it will pull/deploy your image, taking care of wiring the temporal endpoint. We set TEMPORAL_HOST_URL and TEMPORAL_NAMESPACE envs.

The other thing it can optional do is build your worker client. You need to provide build registry, git repository, setup some secrets, etc.

This is a very new endpoint so we are looking for feedback as well on what you think would be helpful for managing your temporal workers via operator?

Here is working CR example of TemporalWorkerProcess
```
apiVersion: temporal.io/v1beta1
kind: TemporalWorkerProcess
metadata:
  name: test
spec:
  builder:
    attempt: 3
    buildDir: samples-go/helloworld
    buildRegistry:
      passwordSecretRef:
        key: PASSWORD
        name: docker-password
      repository: docker.io
      username: ktenzer
    enabled: false
    gitRepository:
      reference:
        branch: main
      url: https://github.com/ktenzer/samples-go.git
    image: quay.io/podman/stable
    version: latest
  clusterRef:
    name: prod
    namespace: temporal
  image: ktenzer/helloworld-worker
```
