### ISSUE TITLE
Add default resource config for ui and admintools

### ISSUE THREAD

**Issue by DodgeCamaro** [alexandrevilain/temporal-operator#366]
As a best practise, would be grate have default resources of ui and admintools

Example
```
resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi
```
