### ISSUE TITLE
Default memory resources not enough for startup temporal operator

### ISSUE THREAD

**Issue by DodgeCamaro** [alexandrevilain/temporal-operator#413]
I've changed resources for temporal operator, due to the service restarting with OOM
Below you can find the resources configuration for temporal-operator
```
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
```
