### ISSUE TITLE
How to configure archival in TemporalCluster

### ISSUE THREAD

**Issue by yujunz** [alexandrevilain/temporal-operator#419]
Not sure if we can leverage https://alexandrevilain.github.io/temporal-operator/features/overrides/ but the configuration is an inline yaml which is difficult to patch.

```
kind: ConfigMap
metadata:
  name: temporal-config
apiVersion: v1
data:
  config_template.yaml: |
    global:
...
```
