### ISSUE TITLE
How to show the temporal-system namespace in the UI

### ISSUE THREAD

**Issue by yujunz** [alexandrevilain/temporal-operator#496]
How do we configure temporal cluster to show `temporal-system` with the operator?

> `docker run --network host -e TEMPORAL_SHOW_TEMPORAL_SYSTEM_NAMESPACE=true temporalio/ui:0.9.0`

https://github.com/temporalio/ui/issues/314#issuecomment-1092321737

**Comment by yujunz** [comment]
Overrides seems not working.

```
  services:
    ui:
      overrides:
        deployment:
...
```
results in 
```
strict decoding error: unknown field "spec.services.ui"
```

**Comment by alexandrevilain** [comment]
Hi @yujunz !
Coud you try with the following config?
```yaml
apiVersion: temporal.io/v1beta1
kind: TemporalCluster
metadata:
  name: prod
  namespace: demo
spec:
  version: 1.21.2
  numHistoryShards: 1
  ui:
    enabled: true
    overrides:
      deployment:
        spec:
          template:
            spec:
              containers:
              - name: ui
                env:
                - name: TEMPORAL_SHOW_TEMPORAL_SYSTEM_NAMESPACE
                  value: "true"
```

It should work.
But I think that we can add a `spec.ui.showTemporalSystemNamespace` to the operator's API.
