### ISSUE TITLE
mTLS options show diff in argocd

### ISSUE THREAD

**Issue by yujunz** [alexandrevilain/temporal-operator#501]
It seems the operator will marshal the values to full representation of the duration. It causes diff in argocd. I would expect it keep the value as input and convert internally if needed.

![Screenshot 2023-09-11 at 09 45 25](https://github.com/alexandrevilain/temporal-operator/assets/6813397/9375aac0-b97e-4066-8e62-1af993040bf7)

The current workaround is manually convert the duration to full format on input.

**Comment by alexandrevilain** [comment]
Seems there is no easy solution we can do on the operator side ... 
Did you checked https://github.com/argoproj/argo-cd/discussions/14229 ?

**Comment by ElanHasson** [comment]
I ran into this. Just set the values in your yaml to match what it gets changed to. argo just trims the unnecessary values.

**Comment by bmorton** [comment]
I ran into this as well and set the values to match as @ElanHasson did.  That ArgoCD issue that you linked works for me as well if I add this:

```yaml
  ignoreDifferences:
    - group: temporal.io
      kind: TemporalCluster
      jsonPointers:
        - /spec/mTLS/certificatesDuration
        - /spec/mTLS/renewBefore
```

Can we close this out if we document these caveats for ArgoCD somewhere?  I'm happy to contribute a doc page on this.
