### ISSUE TITLE
Failed to connect to Postgres 15 that requires ssl

### ISSUE THREAD

**Issue by yujunz** [alexandrevilain/temporal-operator#516]
It seems trying to create a no encryption connect and fails when server requires ssl.

```
2023-09-21T08:54:19.376Z	ERROR	Unable to connect to SQL database.	{"error": "pq: no pg_hba.conf entry for host \"***\", user \"temporal_aws_prod\", database \"temporal_aws_prod\", no encryption", "logging-call-at": "handler.go:52"}
```

Local login with psql works with default option works.

```
psql -d "host=temporal.***.us-west-1.rds.amazonaws.com port=5432 dbname=temporal_aws_prod user=temporal_aws_prod"
Password for user temporal_aws_prod:
psql (15.4, server 15.3)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, compression: off)
Type "help" for help.

temporal_aws_prod=>
```

**Comment by alexandrevilain** [comment]
Hi @yujunz !
Could you please share me your `TemporalCluster` manifest ? 
Thanks.

**Comment by yujunz** [comment]
```
apiVersion: temporal.io/v1beta1
kind: TemporalCluster
metadata:
  name: temporal
spec:
  version: 1.21.5
  numHistoryShards: 512
  persistence:
    defaultStore:
      sql:
        user: temporal_aws_prod
        pluginName: postgres12
        databaseName: temporal_aws_prod
        connectAddr: temporal.***.us-west-1.rds.amazonaws.com:5432
        connectProtocol: tcp
        maxConnLifetime: 1h0m0s
        maxConns: 20
        maxIdleConns: 10
      passwordSecretRef:
        name: temporal-aws-prod-db-password
        key: db-password
      skipCreate: true
    visibilityStore:
      sql:
        user: temporal_aws_prod
        pluginName: postgres12
        databaseName: temporal_aws_prod_visibility
        connectAddr: temporal.***.us-west-1.rds.amazonaws.com:5432
        connectProtocol: tcp
        maxConnLifetime: 1h0m0s
        maxConns: 20
        maxIdleConns: 10
      passwordSecretRef:
        name: temporal-aws-prod-db-password
        key: db-password
      skipCreate: true
  ui:
    enabled: true
    version: latest
  admintools:
    enabled: true
  metrics:
    enabled: true
    prometheus:
      listenPort: 9090
      scrapeConfig:
        serviceMonitor:
          enabled: true
          labels:
            team: temporal
```
