### ISSUE TITLE
Schema create job does not complete when mTLS provider is linkerd

### ISSUE THREAD

**Issue by MichaelCombs28** [alexandrevilain/temporal-operator#524]
The `create-default-database` job fails to complete when running in a linkerd environment since linkerd keeps the job from completing. I haven't figured out how to override the job schema and it's not specified in the docs, so I may be assuming something that is wrong here.

We cannot disable linkerd on jobs due to how our internal networking is setup, we need it to access the persistence store.

We can wrap the script with `linkerd-await` which will allow the job to [terminate gracefully](https://linkerd.io/2.14/tasks/graceful-shutdown/#configuration-options-for-graceful-shutdown)

I'm wondering what you think the best options are here, or if this feature either overrides or await are added when the mTLS provider is linkerd.

As of now, we've disabled the standard create job and have taken the generated yaml and manually done this ourselves.

**Comment by alexandrevilain** [comment]
Hi!

Did you set the `spec.mTLS.provider: linkerd` in your `TemporalCluster` spec ? 

If the answer is yes, this is a bug, because it should be supported: https://github.com/alexandrevilain/temporal-operator/blob/main/internal/resource/persistence/template.go#L316

**Comment by MichaelCombs28** [comment]
The template created for create-database-default.

```bash
#!/bin/bash
temporal-sql-tool --endpoint="<db endpoint>" --port="<db port>" --user="<db user>" --password="$TEMPORAL_DEFAULT_DATASTORE_PASSWORD" --database="<db name>" --plugin="<db type>" create
```

Cluster config

```yml
apiVersion: v1
items:
  - apiVersion: temporal.io/v1beta1
    kind: TemporalCluster
    spec:
      numHistoryShards: 1
      persistence:
        defaultStore:
          sql:
            ...sql config
        visibilityStore:
          ... visibility config 
      admintools:
        enabled: true
      ui:
        enabled: true
      mTLS:
        provider: linkerd
```

I'll create a PR
