### ISSUE TITLE
Delete linked TemporalNamespace when a TemporalCluster is deleted

### ISSUE THREAD

**Issue by vinimona** [alexandrevilain/temporal-operator#552]
We noticed that the TemporalNamespace gets created using the TemporalNamespace CRD in the manifest, but we are unable to delete it and we end up cleaning up a kubernetes namespace which is not an option always if there are other services running in the same namespace.

Used the below manifest and command `kubectl apply -f temporal-namespace.yaml -n temporal-dev` to create/register a temporal namespace:
```
apiVersion: temporal.io/v1beta1
kind: TemporalNamespace
metadata:
  name: myTemporalNamespace
spec:
  clusterRef:
    name: temporalclusterdev
  description: Default namespace for my Service.
  retentionPeriod: 8760h
```

When we run `kubectl delete -f temporal-namespace.yaml -n temporal-dev`, it always get stuck and the custom resource is never deleted from kubernetes.

Thanks.
