### ISSUE TITLE
Is it possible to import current cluster to temporal operator ?

### ISSUE THREAD

**Issue by mfractal** [alexandrevilain/temporal-operator#562]
we have a production cluster deployed via helm chart, i'd like to migrate to use the operator without any downtime if possible. what would be the best path to do it ?

**Comment by alexandrevilain** [comment]
Hi! 

I never did that but it *could* be doable. Let's try this! 

What I could suggest to you:

Create a new `TemporalCluster` on a dev cluster (with brand new storage) and fill the spec fields to make the operator generate a  configmap that looks like (as much as possible) with the current running cluster configmap (the config generated by the helm chart). The only diff should be database users, password and endpoints. If you have diff on the configmap, please raise them on this issue. Maybe we have missing feature on the operator spec.

Then try to make services managed by the operator to join your existing cluster.  To do that, create a new `TemporalCluster` with the spec you filled on the dev cluster. The operator will try to configure the database for you. To make it skip the persistence reconciliation, update the `TemporalCluster`'s status with the following fields:
```yaml
    persistence:
      defaultStore:
        created: true
        schemaVersion: 1.21.2
        setup: true
        type: postgres
      visibilityStore:
        created: true
        schemaVersion: 1.21.2
        setup: true
        type: postgres
```
(update it with the right values).
This will make the operator to only deploy the components.

If the services deployed by the operator have successfully joined the current existing cluster you'll be able to uninstall the helm chart.

I have no clue if it could work, let's try this :)
