### ISSUE TITLE
Add Custom Search Attributes to TemporalNamespace

### ISSUE THREAD

**Issue by dmytro-orlenko** [alexandrevilain/temporal-operator#567]
Custom Search Attributes as a part of namespace and can help to search workflow by attributes

```
apiVersion: temporal.io/v1beta1
kind: TemporalNamespace
metadata:
  name: default
spec:
  clusterRef:
    name: temporal
  description: Default namespace
  retentionPeriod: 336h #14 days
  allowDeletion: false
  customSearchAttributes:
    key: value
```
