### ISSUE TITLE
Deployment Issue with persistence tls enabled - client cert and key

### ISSUE THREAD

**Issue by mbalamaruthu** [alexandrevilain/temporal-operator#626]
Seeing below error when deploying wit persistence tls client certs enabled - certFileRef and keyFileRef.

```
0s          Warning   ProcessingError          temporalcluster/temporal                                   Job.batch "temporal-create-default-database" is invalid: [spec.template.spec.containers[0].volumeMounts[2].mountPath: Invalid value: "/etc/tls/datastores/default": must be unique, spec.template.spec.containers[0].volumeMounts[3].mountPath: Invalid value: "/etc/tls/datastores/default": must be unique, spec.template.spec.containers[0].volumeMounts[5].mountPath: Invalid value: "/etc/tls/datastores/visibility": must be unique, spec.template.spec.containers[0].volumeMounts[6].mountPath: Invalid value: "/etc/tls/datastores/visibility": must be unique]
``` 

We probably need unique volume mount paths for each cert/key file or may be projected volumes to handle this. Thanks.

Here is the persistence configuration
```
persistence:
  defaultStore:
    tls:
      enabled: true
      serverName: "mysqllocalhost"
      enableHostVerification: true
      caFileRef:
        name: temporal-persistence-tls
        key: ca.crt
      certFileRef:
        name: temporal-persistence-tls
        key: client.crt
      keyFileRef:
        name: temporal-persistence-tls
        key: client.key
```
