### ISSUE TITLE
Unable to create workspace using TemporalNamespace CRD

### ISSUE THREAD

**Issue by danielrearden** [alexandrevilain/temporal-operator#631]
Here's the namespace:

```yaml
apiVersion: temporal.io/v1beta1
kind: TemporalNamespace
metadata:
  name: default
  namespace: contra
spec:
  clusterRef:
    name: '{{ .Release.Name }}'
    namespace: contra
  description: Default namespace
  retentionPeriod: 168h # 7 days
```

and the cluster:

```yaml
apiVersion: temporal.io/v1beta1
kind: TemporalCluster
metadata:
  labels:
  # {{ include "app.resource_labels" . | indent 4 }}
  name: '{{ .Release.Name }}'
spec:
  admintools:
    enabled: false
    image: 'temporalio/admin-tools'
  # https://docs.temporal.io/references/dynamic-configuration
  dynamicConfig:
    pollInterval: 10s
    values:
      matching.numTaskqueueReadPartitions:
        - constraints: {}
          value: 4
      matching.numTaskqueueWritePartitions:
        - constraints: {}
          value: 4
  image: 'temporalio/server'
  log:
    level: debug
  numHistoryShards: 1
  persistence:
    defaultStore:
      passwordSecretRef:
        key: *****
        name: '{{ .Release.Name }}'
      sql:
        connectAddr: *****
        connectProtocol: tcp
        databaseName: temporal
        maxConnLifetime: '1h0m0s'
        maxConns: 57
        maxIdleConns: 50
        pluginName: postgres
        user: *****
    visibilityStore:
      passwordSecretRef:
        key: *****
        name: '{{ .Release.Name }}'
      sql:
        connectAddr: *****
        connectProtocol: tcp
        databaseName: temporal_visibility
        maxConnLifetime: '1h0m0s'
        maxConns: 57
        maxIdleConns: 50
        pluginName: postgres
        user: *****
  services:
    frontend:
      membershipPort: 6933
      port: 7233
    history:
      membershipPort: 6934
      port: 7234
    matching:
      membershipPort: 6935
      port: 7235
    worker:
      membershipPort: 6939
      port: 7239
  ui:
    enabled: true
  version: 1.22.4
```

However, the namespace is not created. I can see the following logs coming from the controller-manager
```
2024-02-09T11:33:02Z	INFO	Starting reconciliation	{"controller": "temporalnamespace", "controllerGroup": "temporal.io", "controllerKind": "TemporalNamespace", "TemporalNamespace": {"name":"default","namespace":"contra"}, "namespace": "contra", "name": "default", "reconcileID": "34b372d7-cdf4-4a8b-bfe1-1494efa11dac"}2024-02-09T11:33:02Z	INFO	Skipping namespace reconciliation until referenced cluster is ready	{"controller": "temporalnamespace", "controllerGroup": "temporal.io", "controllerKind": "TemporalNamespace", "TemporalNamespace": {"name":"default","namespace":"contra"}, "namespace": "contra", "name": "default", "reconcileID": "34b372d7-cdf4-4a8b-bfe1-1494efa11dac"}
```

I can see the following `status` on the TemporalCluster itself:

```
status:
  conditions:
    - lastTransitionTime: '2024-02-09T11:23:41Z'
      message: ''
      observedGeneration: 8
      reason: ServicesNotReady
      status: 'False'
      type: Ready
    - lastTransitionTime: '2024-02-09T03:34:20Z'
      message: ''
      observedGeneration: 8
      reason: LastReconcileCycleSucceded
      status: 'True'
      type: ReconcileSuccess
  persistence:
    defaultStore:
      created: true
      schemaVersion: 1.22.4
      setup: true
      type: postgres
    visibilityStore:
      created: true
      schemaVersion: 1.22.4
      setup: true
      type: postgres
  services:
    - name: frontend
      ready: true
      version: 0.0.0
    - name: history
      ready: true
      version: 0.0.0
    - name: matching
      ready: true
      version: 0.0.0
    - name: worker
      ready: true
      version: 0.0.0
```

So it's clear that the namespace isn't getting created because the namespace reconciliation is being skipped because the cluster is not showing as ready. However, all the services are up and healthy so I'm not sure why we're getting into this state.

Enabling the admin tools does not resolve the above, and additionally results in the following warnings logged from the cluster:

```
container admintools is not valid for pod contra-temporal-operator-frontend-575b7bbcc6-njd5q
container admintools is not valid for pod contra-temporal-operator-history-7f5c446fc8-56q55
container admintools is not valid for pod contra-temporal-operator-matching-59c48667d-txfv4
container admintools is not valid for pod contra-temporal-operator-ui-6f9cfcbc7-v7m9q
container admintools is not valid for pod contra-temporal-operator-worker-dcc6767d6-9wk8d
```

**Comment by alexandrevilain** [comment]
Hi @danielrearden, by looking at:
```
conditions:
    - lastTransitionTime: '2024-02-09T11:23:41Z'
      message: ''
      observedGeneration: 8
      reason: ServicesNotReady
      status: 'False'
      type: Ready
```

Looks like some of the Temporal Services are not ready (frontend, history or matching). Could you please check your pods status ? If they are running, could you please check their logs ?

Thanks
