### ISSUE TITLE
Using Custom elastic search indices breaks GetPasswordEnvVarName() 

### ISSUE THREAD

**Issue by umizoom** [alexandrevilain/temporal-operator#634]
## What

When setting a custom index for elastic search like so:

```
    visibilityStore:
      elasticsearch:
        version: v7
        username: some_user
        url: some_url
        indices:
          visibility: temporal_visibility_v1
```

We noticed `schema-scripts` config map does not render correctly. Specially the `--password="$TEMPORAL__DATASTORE_PASSWORD"`. It should be `--password="$TEMPORAL_DEFAULT_DATASTORE_PASSWORD"`. I think its a issue with when the function `GetPasswordEnvVarName() `  gets called. I am not sure where however. 

The operator breaks due to unset `$TEMPORAL__DATASTORE_PASSWORD` with:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
```

## To reproduce 

You should be able to hit this issue by just adding the following nested key in the elastic search block for the TemporalCluster resource.

```
        indices:
          visibility:
```

## Update

We ended up working around the `$TEMPORAL__DATASTORE_PASSWORD`  issue by setting the `name` key for each `persistence` store. 

Example:

```
  persistence:
    defaultStore:
      name: default
      sql:
        user: some_user
        pluginName: postgres12
        databaseName: some_db
        connectAddr: some_url
        connectProtocol: tcp

    visibilityStore:
      name: visibility
      elasticsearch:
        version: v7
        username: same_user
        url: some_url
```

This fixed the env vars in the `schema-scripts` config map. However we still see the error below when we define a custom `indices`. 

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
```

Thank you!
