### ISSUE TITLE
Can't create temporal namespace when using mTLS and custom certs

### ISSUE THREAD

**Issue by helenyugithub** [alexandrevilain/temporal-operator#688]
We have enabled mTLS with cert-manager but have injected our own certificates using the following configuration

```
  ui:
    enabled: true
    overrides:
      deployment:
        spec:
          template:
            spec:
              volumes:
                - name: ui-mtls-certificate
                  secret:
                    secretName: temporal-certificate-override
  admintools:
    enabled: true
    overrides:
      deployment:
        spec:
          template:
            spec:
              volumes:
                - name: admintools-mtls-certificate
                  secret:
                    secretName: temporal-certificate-override
  mTLS:
    provider: cert-manager
    internode:
      enabled: true
    frontend:
      enabled: true
  services:
    overrides:
      deployment:
        spec:
          template:
            spec:
              volumes:
                - secret:
                    secretName: trust-ca
                  name: internode-intermediate-ca-certificate # This contains the PK of the certificate authorities that the pod wants to trust
                - secret:
                    secretName: temporal-certificate-override
                  name: internode-certificate
                - secret:
                    secretName: trust-ca
                  name: frontend-intermediate-ca-certificate # This contains the PK of the certificate authorities that the pod wants to trust
                - secret:
                    secretName: temporal-certificate-override
                  name: frontend-certificate
                - secret:
                    secretName: temporal-certificate-override
                  name: worker-mtls-certificate
```

This works end to end (external client, UI, tctl in admin tools), but we're having trouble with the operator creating TemporalNamespaces, presumably because the `temporal-operator-controller-manager` doesn't have the right certs. Note that I'm not sure that this works even in the vanilla mTLS setup, given that I don't see how the temporal-operator-controller-manager gets any certs at all.
