### ISSUE TITLE
Support creating default namespace using the CRD

### ISSUE THREAD

**Issue by alexandrevilain** [alexandrevilain/temporal-operator#72]
When we spin up a temporal cluster, we have to create namespaces using tctl or with custom code using the SDK.
It can be a great feature if the operator can create them.
For instance:
```yaml
apiVersion: apps.alexandrevilain.dev/v1alpha1
kind: TemporalCluster
metadata:
  name: prod
  namespace: demo
spec:
  version: 1.17.0
  numHistoryShards: 1
  [...]
  namespaces:
    - default
    - accounting

```
