### ISSUE TITLE
How can I rollout Temporal 1.24.2 version?

### ISSUE THREAD

**Issue by Kiseloff** [alexandrevilain/temporal-operator#771]
Hi, @alexandrevilain !
I have your operator v0.19.0. Can I rollout Temporal Server v1.24.2 using it?

I've set `version: 1.24.2` and got an error:
```
# temporalclusters.temporal.io "temporal" was not valid:
# * spec.version: Forbidden: Unsupported temporal version (supported: >=1.14.0 <1.24.0)
```

**Comment by alexandrevilain** [comment]
Hi @Kiseloff !

1.24.x is not supported for now but this is Work in progress: https://github.com/alexandrevilain/temporal-operator/pull/760

**Comment by sotatek-hungpham5** [comment]
Hi guys,
How can I choose the temporal version?
I added the version config to TemporalCluster but when I deployed it, the image was still 1.21.5 ?
```
apiVersion: temporal.io/v1beta1
kind: TemporalCluster
metadata:
  name: temporal-cassandra
  namespace: dev-hung
spec:
  version: 1.23.0
```
