### ISSUE TITLE
Support for autoscaling (HPA)

### ISSUE THREAD

**Issue by jakub-dibala** [alexandrevilain/temporal-operator#774]
We need to autoscale the matching service. So I deployed HPA to cluster, but it does not work correctly.

When `replicas` is set on deployment spec, HPA will not work - as you can read here: https://stackoverflow.com/a/76548515. It interferes with replica set.

I tried to apply a override:
```yaml
spec:
  services:
    matching:
      overrides:
        deployment:
          spec:
            replicas:
```

to delete a replica count on deployment, but helm warns me:
`W0712 12:28:20.755105 2402442 warnings.go:70] unknown field "spec.services.matching.overrides.deployment.spec.replicas"`. 
Even if I try to set an override to a specific number, it fails with this error.

Can you please guide me, how can I set autoscaling to a specific temporal service? Thanks.

**Comment by alexandrevilain** [comment]
Hi @jakub-dibala !

Thanks for reporting this issue.

I think that with current operator behavior, this is not feasible. But I think that it could be easily integrated with the controller.

The integration could be very basic at the first implementation, then we could think about managing HPA within the controller.

The first implementation could provide the following API:

```yaml
spec:
  services:
    matching:
      autoscaling: {}
```

Setting `autoscaling` would make the controller bypass the `replicas` field on deployments.

Then the second implementation could provide a more complete API that would allow user to configure HPA behavior:

```yaml
spec:
  services:
    matching:
      autoscaling:
        minReplicas: 1
        maxReplicas: 10
        metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
```

WDYT ?
