### ISSUE TITLE
Failed to connect to Postgres 16 that requires ssl

### ISSUE THREAD

**Issue by ujala-singh** [alexandrevilain/temporal-operator#791]
I am getting below error on setup schema pod:

```
k logs -f temporal-dev-setup-default-schema-drw9m      
2024-08-20T10:30:09.436Z	ERROR	Unable to connect to SQL database.	{"error": "pq: pg_hba.conf rejects connection for host \"10.42.0.41\", user \"temporal_admin\", database \"temporal\", no encryption", "logging-call-at": "handler.go:52"}
```
TemporalCluster Manifest:

```
apiVersion: temporal.io/v1beta1
kind: TemporalCluster
metadata:
  name: temporal-dev
  namespace: temporal
spec:
  version: 1.23.0
  numHistoryShards: 512
  persistence:
    defaultStore:
      sql:
        user: temporal_admin
        pluginName: postgres12
        databaseName: temporal
        connectAddr: temporal-backend.default.svc.cluster.local:5432
        connectProtocol: tcp
        maxConnLifetime: 1h0m0s
        maxConns: 20
        maxIdleConns: 10
      passwordSecretRef:
        name: temporal-default-store
        key: password
      skipCreate: true
      tls:
        enabled: false
    visibilityStore:
      sql:
        user: temporal_admin
        pluginName: postgres12
        databaseName: temporal_visibility
        connectAddr: temporal-backend.default.svc.cluster.local:5432
        connectProtocol: tcp
        maxConnLifetime: 1h0m0s
        maxConns: 20
        maxIdleConns: 10
      passwordSecretRef:
        name: temporal-visibility-store
        key: password
      skipCreate: true
      tls:
        enabled: false
  log:
    level: debug
  ui:
    enabled: true
  admintools:
    enabled: true
  # metrics:
  #   enabled: true
  #   prometheus:
  #     listenPort: 9090
  #     scrapeConfig:
  #       serviceMonitor:
  #         enabled: true
  #         labels:
  #           release: test
  #         metricRelabelings:
  #         - sourceLabels: [__name__]
  #           targetLabel: __name__
  #           replacement: temporal_$1
  dynamicConfig:
    pollInterval: 10s
    values:
      matching.numTaskqueueReadPartitions:
      - value: 5
        constraints: {}
      matching.numTaskqueueWritePartitions:
      - value: 5
        constraints: {}
```
I am able to connect to DB outside temporal:
<img width="1504" alt="Screenshot 2024-08-20 at 4 05 10 PM" src="https://github.com/user-attachments/assets/adfc5a0c-cdcb-4fa5-80cc-26a655103d70">

Related issue: https://github.com/zalando/postgres-operator/issues/2734
