### ISSUE TITLE
services.worker does not allow override of TEMPORAL_ADDRESS env variable when using internalFrontend

### ISSUE THREAD

**Issue by dlydiard** [alexandrevilain/temporal-operator#914]
TemporalCluster
```yaml
         spec:
            services:
              internalFrontend:
                enabled: true
              frontend:
                replicas: 3
              worker:
                replicas: 3
                overrides:
                  deployment:
                    spec:
                      template:
                        spec:
                          containers:
                            - name: service
                              # env:
                              #   - name: USE_INTERNAL_FRONTEND
                              #     value: "1"
                              #   - name: TEMPORAL_ADDRESS
                              #     value: temporal-internal-frontend:7233
```

Results in the TemporalCluster reporting the error
```
Deployment.apps "temporal-worker" is invalid: [spec.template.spec.containers[0].env[0].valueFrom: Invalid value: "": may not be specified when `value` is not empty, spec.template.spec.containers[0].env[2].valueFrom: Invalid value: "": may not have more than one field specified at a time, spec.template.spec.containers[0].env[3].valueFrom: Invalid value: "": may not be specified when `value` is not empty]
```

When internalFrontend is enabled (for auth with the default claimMapper), I had to manually set TEMPORAL_ADDRESS in both the UI and adminTools containers. Should this be automatic? Also, the worker service isn’t using internalFrontend, and I can’t override its environment variables—any known workaround? I suspect the issue is in the env var merge logic (it seems to work fine for all other services).

**Comment by ujala-singh** [comment]
@dlydiard It should pick automatically the internal frontend service if internalFrontend is enabled. If not try to override the worker deployment like below:
```
worker:
  overrides:
    deployment:
      spec:
        template:
          spec:
            containers:
            - name: service
              envFrom:
                - secretRef:
                    name: temporal-worker-config
```

Define all of the env in the defined secret `temporal-worker-config`.
